### PR TITLE
Fix Travis CI

### PR DESCRIPTION
**Pull request by paragonie-scott**

### CODE REVIEW

**Comment by paragonie-scott** [comment]
I have no idea what I was thinking earlier when I wrote those bash conditionals, but it clearly wasn't correct.

**Comment by paragonie-scott** [comment]
This is frustrating. There doesn't seem to be a way to add `display_startup_errors = 0` to the temporary php.ini created by the makefile, since it if exists, it blanks it out.

**Comment by paragonie-scott** [comment]
I think the best thing to do here is, nothing. The startup errors aren't going away, might as well make this only target < 7.2 and expect everyone else to install it with PHP.

**Comment by nikic** [comment]
Or does Travis compile sodium as a static extension? In that case yeah, not testing on >= 7.2 is probably the only thing you can do (short of building a separate PHP without sodium).

**Pull request merged**
