### PR TITLE
Add release notes for 1.0.0 and 1.0.1

### PR DESCRIPTION
**Pull request by paragonie-scott**

### CODE REVIEW

**Comment by jedisct1** [comment]
:+1:

**Comment by paragonie-scott** [comment]
I'll update the documentation this evening to cover the new features. :)

**Comment by jedisct1** [comment]
Maybe `sodium_compare()` would be worth adding before we tag a new release?

**Comment by paragonie-scott** [comment]
Yeah, I could see that being incredibly useful. Do you want to add it or shall I send a PR? :)

**Comment by jedisct1** [comment]
Go ahead :)

**Pull request merged**
