### PR TITLE
Expose crypto_pwhash with libsodium 1.0.9 and newer

### PR DESCRIPTION
**Pull request by paragonie-scott**
See #72

### CODE REVIEW

**Comment by jedisct1** [comment]
Just one thing: `crypto_pwhash_str()` slightly differs from the scrypt version.

The scrypt string format has a fixed length no matter what the parameters are.

The argon2 string format has a variable length, because parameters are directly stored as decimal values. That's a bit annoying, but it's probably too late for them to change the specifications.

`crypto_pwhash_strbytes()` returns the maximum possible string length (including the final `\0`), and `crypto_pwhash_str()` pads with zeros.

`crypto_pwhash_verify()` doesn't care, as strings a zero-terminated anyway.

I'm not sure whether the PHP bindings should return a fixed-length string, with the padding, or just the required string length. Your code currently does the former. This is fine, but these extra zeros have to be removed or escaped in order to appear in SQL queries, which is not an unreasonable way to use the output of these functions.

**Comment by paragonie-scott** [comment]
> The argon2 string format has a variable length, because parameters are directly stored as decimal values. That's a bit annoying, but it's probably too late for them to change the specifications.

Ah, yeah, thanks for pointing that out.

> `crypto_pwhash_strbytes()` returns the maximum possible string length (including the final `\0`), and `crypto_pwhash_str()` pads with zeros.

Then the right thing to do, in my opinion, is strip the excess `\0` bytes.

> This is fine, but these extra zeros have to be removed or escaped in order to appear in SQL queries, which is not an unreasonable way to use the output of these functions.

Well, is kind of is. :)

xkcd-327b

**Comment by paragonie-scott** [comment]
Quick question: Is there a function in libsodium that returns the *actual* length of the returned argon2i hash? Or do I have to implement a "strip right padding, then make sure only 1 `NUL` remains" workaround?

**Comment by jedisct1** [comment]
There is: `strlen()` :)

**Comment by paragonie-scott** [comment]
Oh, right. Okay, no more all-nighters for Scott. :)

**Comment by paragonie-scott** [comment]
Not sure if my variable name choice is okay or not.

I also might want to add a memzero() on the hash that gets returned after copying it to the appropriately sized zend_string.

**Comment by jedisct1** [comment]
I don't think the copy is necessary. We can probably allocate the maximum size and then use some PHP macro to truncate the string.

**Comment by paragonie-scott** [comment]
@remicollet Is there a PHP macro to resize a string?

**Comment by jedisct1** [comment]
Yup: `ZSTR_TRUNCATE(string, len)`

**Comment by paragonie-scott** [comment]
Wow, I feel dopey.

**Comment by paragonie-scott** [comment]
Okay, how does this look?

**Comment by jedisct1** [comment]
Hi Scott,

And sorry for the delayed response. Was traveling without my laptop.

Looks good! Thanks a lot for your help!

Merging now.

**Pull request merged**
