### PR TITLE
crypto_pwhash_scryptsalsa208sha256_ll

### PR DESCRIPTION
**Pull request by gilacost**

### CODE REVIEW

**Comment by the-djmaze** [comment]
I know this is old and i understand why you rejected this code.
However, it is something i am looking for after this discussion https://github.com/jedisct1/libsodium/issues/599
Because i've use a different extension https://github.com/DomBlack/php-scrypt which allowed custom salt lengths in PHP.
See for example https://github.com/DomBlack/php-scrypt/blob/master/scrypt.php

Since PHP 7.2 now gets libsodium it would be nice to allow me to use the old scrypt hashes.

**Comment by paragonie-scott** [comment]
I would, personally, explore building a userland wrapper for php-scrypt compatibility. You should be able to with just `crypto_pwhash_scryptsalsa208sha256()` rather than a `crypto_pwhash_scryptsalsa208sha256_str()` variant.

If you need the same encoding, https://github.com/paragonie/constant_time_encoding/blob/master/src/Base64DotSlashOrdered.php should be compatible.

**Comment by the-djmaze** [comment]
Yes, i have pure PHP code that generates an scrypt hash but takes seconds.
That way i don't need the mentioned php-scrypt and can convert them to crypto_pwhash_scryptsalsa208sha256 or crypto_pwhash_scryptsalsa208sha256_str
However, for users it would just mean the first new login takes a lot of seconds.
Having crypto_pwhash_scryptsalsa208sha256_ll() available in PHP makes live a lot easier with current  implementations.

**Comment by paragonie-scott** [comment]
You might want to consider just [adopting this strategy for legacy hash rotation](https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016#legacy-hashes) and keep both installed for a reasonable transition period.

**Comment by jedisct1** [comment]
FYI scrypt has been removed from the PECL sodium extension, and the one bundled with php will follow.

If you really want to scrypt, use a dedicated extension.

**Pull request closed without merging**
