### PR TITLE
Add crypto_sign_ed25519_*_to_curve25519()

### PR DESCRIPTION
**Pull request by paragonie-scott**
See #55 

EDIT: Travis is stuck (won't even start yet), but the test passed locally. I'm not sure if you'd like a much more rigorous test case before merging it.

### CODE REVIEW

**Comment by jedisct1** [comment]
/me reinstalls a Vagrant box for php dev, says to himself "ok, I really have to address #55 now, it's been almost a week, it's ridiculous".
/me glances at his Github notifications.
/me is happy. Superscott already did it :)

**Comment by bitbeans** [comment]
@Superscott :+1:

**Comment by superscott** [comment]
side note, @paragonie-scott is not @superscott -- but either way, i'm sure he is super as well :D

**Comment by sergeyklay** [comment]
:laughing:

**Comment by bitbeans** [comment]
@superscott i did not know this username exists :)

**Pull request merged**
