### PR TITLE
Increase PHP version constraint

### PR DESCRIPTION
**Pull request by paragonie-security**
https://github.com/jedisct1/libsodium-php/issues/220#issuecomment-1478612844

### CODE REVIEW

**Comment by jedisct1** [comment]
Thank you!

**Comment by MrMEEE** [comment]
We need a new version released, so we can install libsodium on php >8.0.99.. Can you please release a new version?

**Comment by celosauro** [comment]
> We need a new version released, so we can install libsodium on php >8.0.99.. Can you please release a new version?

RT

**Comment by Strelox** [comment]
@jedisct1 can we expect a new release with this changeset? PHP 8.0 is EOL and without a new release this extension is not installable on current php versions.

**Comment by jedisct1** [comment]
It's included in PHP since version 7.2

**Comment by mrd83** [comment]
> It's included in PHP since version 7.2

Yes, on one teeny-tiny condition: php compiled with `--with-sodium=` option. Unfortunately php from the official ROCKY/Alma linux (Centos descendants) deas not include it. I can prove it - but let's assume that if I had to compile sodium module manually - I'm telling the truth ;]

Knowing the above - the main problem is: there's no sodium.so available for php 8.1 and 8.2 (not even mentioning 8.3 or 8.4). 

Question: will you maintain this repository? If not - are you willing to allow me to do it?

**Pull request merged**
