### PR TITLE
Add \Sodium\compare()

### PR DESCRIPTION
**Pull request by paragonie-scott**

### CODE REVIEW

**Comment by jedisct1** [comment]
Hey Scott, the whole point of `sodium_compare()` is to return `-1`, `0` or `1`, not a boolean :)

**Comment by paragonie-scott** [comment]
Oh. I see.

**Comment by paragonie-scott** [comment]
Okay, the tests pass in my Debian VM, and its output is intuitive.

**Comment by jedisct1** [comment]
Perfect :+1: 

Thanks, Scott!

**Pull request merged**
